// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Comment *string `json:"comment,omitempty"`
}

type NewComment struct {
	UserName string `json:"user_name"`
	Comment  string `json:"comment"`
}

type NewUser struct {
	UserName string `json:"user_name"`
}

type User struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Favorites *string `json:"favorites,omitempty"`
}

type UserUpdate struct {
	UserName  string  `json:"user_name"`
	Favorites *string `json:"favorites,omitempty"`
}
