// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID          int    `json:"id"`
	CreatedAt   string `json:"created_at"`
	CommentedTo int    `json:"commented_to"`
	Comment     string `json:"comment"`
}

type NewComment struct {
	CommentTo int    `json:"comment_to"`
	UserName  string `json:"user_name"`
	Comment   string `json:"comment"`
}

type NewUser struct {
	UserName string `json:"user_name"`
}

type User struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	Favorites []int  `json:"favorites"`
}

type UserUpdate struct {
	UserName  string  `json:"user_name"`
	Favorites *string `json:"favorites,omitempty"`
}
