// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID          int    `json:"id"`
	UserName    string `json:"user_name"`
	CreatedAt   string `json:"created_at"`
	CommentedTo string `json:"commented_to"`
	Comment     string `json:"comment"`
}

type Image struct {
	ImgName     string     `json:"img_name"`
	FavoriteCnt int        `json:"favorite_cnt"`
	Comments    []*Comment `json:"comments"`
}

type NewComment struct {
	CommentTo string `json:"comment_to"`
	UserName  string `json:"user_name"`
	Comment   string `json:"comment"`
}

type NewUser struct {
	UserName string `json:"user_name"`
}

type User struct {
	ID        int      `json:"id"`
	Name      string   `json:"name"`
	Favorites []string `json:"favorites"`
}

type UserUpdate struct {
	UserName  string  `json:"user_name"`
	Favorites *string `json:"favorites,omitempty"`
}
